# conda env create -f environment.yml
# conda activate ml-env

name: ml-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy<2
  - pandas>=1.3
  - scikit-learn>=1.0
  - xgboost>=1.7
  - mlflow>=1.30
  - notebook
  - pip
  - pip:
      - tensorflow==2.12.0
      - tensorflow_datasets==4.9.2
      - keras==2.12.0